#!/usr/bin/env sh
export CLASSPATH="../Compiled/Java_Vensim/:/usr/local/lib/antlr-4.5-complete.jar:$CLASSPATH"
echo $CLASSPATH
antlr4='java -jar /usr/local/lib/antlr-4.5-complete.jar'
grun='java org.antlr.v4.runtime.misc.TestRig'
$grun Model model -tree -gui $1
